#define cmpxchg_uint32 __sync_bool_compare_and_swap
#define cmpxchg_uint64 __sync_bool_compare_and_swap
// #define cmpxchg_float32 __sync_bool_compare_and_swap
// #define cmpxchg_float64 __sync_bool_compare_and_swap